/* Copyright © 2025 Proaled */
#ifndef GAME_CLIENT_COMPONENTS_PROALEDCLIENT_VERSION_H
#define GAME_CLIENT_COMPONENTS_PROALEDCLIENT_VERSION_H

#define PROALEDCLIENT_BUILD_DATE "2025"
#define PROALEDCLIENT_VERSIONNR 100
#define PROALEDCLIENT_VERSION "1.0.0"

#endif
