// This file can be included several times.

#ifndef MACRO_CONFIG_INT
#error "The config macros must be defined"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Flags, Desc) ;
#define MACRO_CONFIG_COL(Name, ScriptName, Def, Flags, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Flags, Desc) ;
#endif

MACRO_CONFIG_INT(PcCustomAspectRatioMode, pc_custom_aspect_ratio_mode, -1, -1, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio mode (-1=legacy auto, 0=off, 1=preset, 2=custom)")
MACRO_CONFIG_INT(PcCustomAspectRatioApplyMode, pc_custom_aspect_ratio_apply_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio apply mode (0=game only, 1=full, 2=game no hud)")
MACRO_CONFIG_INT(PcCustomAspectRatio, pc_custom_aspect_ratio, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Aspect ratio value x100 (0=off, presets: 125=5:4, 133=4:3, 150=3:2, custom: 100-1000)")
MACRO_CONFIG_INT(PcCustomAspectRatioNum, pc_custom_aspect_ratio_num, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio numerator (width), 0=unset")
MACRO_CONFIG_INT(PcCustomAspectRatioDen, pc_custom_aspect_ratio_den, 0, 0, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio denominator (height), 0=unset")

// Chat media
MACRO_CONFIG_INT(PcChatMediaPreview, pc_chat_media_preview, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render media previews from chat links")
MACRO_CONFIG_INT(PcChatMediaPhotos, pc_chat_media_photos, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render photo previews from chat links")
MACRO_CONFIG_INT(PcChatMediaGifs, pc_chat_media_gifs, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render GIF and animated media previews from chat links")
MACRO_CONFIG_INT(PcChatMediaContentFilter, pc_chat_media_content_filter, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Allow chat media previews only from configured domains")
MACRO_CONFIG_STR(PcChatMediaAllowedDomains, pc_chat_media_allowed_domains, 512, "tenor.com; imgur.com; giphy.com", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Semicolon-separated allowlist for chat media domains")
MACRO_CONFIG_INT(PcChatMediaPreviewMaxWidth, pc_chat_media_preview_max_width, 220, 120, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum width of chat media previews")
MACRO_CONFIG_INT(PcChatMediaViewer, pc_chat_media_viewer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable fullscreen media viewer for chat previews")
MACRO_CONFIG_INT(PcChatMediaViewerMaxZoom, pc_chat_media_viewer_max_zoom, 800, 100, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum zoom of the chat media viewer in percent")

MACRO_CONFIG_INT(PcCrystalLaser, pc_crystal_laser, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render rifle and shotgun lasers with crystal shards and icy glow")
MACRO_CONFIG_INT(PcPrevMouseMaxDistance45Degrees, pc_prev_mouse_max_distance_45_degrees, 400, 0, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_INSENSITIVE, "Previous maximum cursor distance for 45 degrees")
MACRO_CONFIG_INT(PcPrevInpMousesens45Degrees, pc_prev_inp_mousesens_45_degrees, 200, 1, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Previous mouse sensitivity for 45 degrees")
MACRO_CONFIG_INT(PcToggle45Degrees, pc_toggle_45_degrees, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use toggle mode for 45 degrees bind")
MACRO_CONFIG_INT(PcPrevInpMousesensSmallSens, pc_prev_inp_mousesens_small_sens, 200, 1, 1000000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Previous mouse sensitivity for small sens")
MACRO_CONFIG_INT(PcToggleSmallSens, pc_toggle_small_sens, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use toggle mode for small sens bind")
MACRO_CONFIG_INT(PcGoresMode, pc_gores_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Entity-like gores mode")
MACRO_CONFIG_INT(PcGoresModeDisableIfWeapons, pc_gores_mode_disable_weapons, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable gores mode when holding shotgun, grenade or laser")
MACRO_CONFIG_INT(PcSpecMovedNotify, pc_spec_moved_notify, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show 'moved in game' warning when someone hooks/hits your character while you are in spectator")
MACRO_CONFIG_INT(PcHookCombo, pc_hook_combo, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show hook combo popups with combo sounds")
MACRO_CONFIG_INT(PcHookComboMode, pc_hook_combo_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook combo trigger mode (0=hook, 1=hammer, 2=hook and hammer)")
MACRO_CONFIG_INT(PcHookComboResetTime, pc_hook_combo_reset_time, 1200, 100, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum time in ms between player hooks before combo restarts")
MACRO_CONFIG_INT(PcHookComboSoundVolume, pc_hook_combo_sound_volume, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook combo sound volume")
MACRO_CONFIG_INT(PcHookComboSize, pc_hook_combo_size, 100, 50, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hook combo popup size")
MACRO_CONFIG_INT(PcCinematicCamera, pc_cinematic_camera, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable smooth cinematic camera movement in spectator freeview")
MACRO_CONFIG_INT(PcAnimations, pc_animations, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle ProaledClient UI animations")
MACRO_CONFIG_INT(PcModuleUiRevealAnimation, pc_module_ui_reveal_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle module settings reveal animations")
MACRO_CONFIG_INT(PcModuleUiRevealAnimationMs, pc_module_ui_reveal_animation_ms, 180, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Module settings reveal time (in ms)")
MACRO_CONFIG_INT(PcIngameMenuAnimation, pc_ingame_menu_animation, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle ingame ESC menu animation")
MACRO_CONFIG_INT(PcIngameMenuAnimationMs, pc_ingame_menu_animation_ms, 220, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Ingame ESC menu animation time (in ms)")
MACRO_CONFIG_INT(PcChatAnimation, pc_chat_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat animation")
MACRO_CONFIG_INT(PcChatAnimationMs, pc_chat_animation_ms, 300, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat animation time (in ms)")
MACRO_CONFIG_INT(PcChatOpenAnimation, pc_chat_open_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat open animation")
MACRO_CONFIG_INT(PcChatOpenAnimationMs, pc_chat_open_animation_ms, 220, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat open animation time (in ms)")
MACRO_CONFIG_INT(PcChatTypingAnimation, pc_chat_typing_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle chat typing animation")
MACRO_CONFIG_INT(PcChatTypingAnimationMs, pc_chat_typing_animation_ms, 180, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat typing animation time (in ms)")
MACRO_CONFIG_INT(PcKillfeedAnimation, pc_killfeed_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle killfeed animation")
MACRO_CONFIG_INT(PcKillfeedAnimationMs, pc_killfeed_animation_ms, 200, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Killfeed animation time (in ms)")
MACRO_CONFIG_INT(PcMainMenuAnimation, pc_main_menu_animation, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle main menu button hover animation")
MACRO_CONFIG_INT(PcMainMenuAnimationSpeed, pc_main_menu_animation_speed, 12, 1, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Main menu hover animation speed")
MACRO_CONFIG_INT(PcChatAnimationType, pc_chat_animation_type, 3, 1, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Chat animation type")

// General visuals
MACRO_CONFIG_INT(PcSettingsLayout, pc_settings_layout, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Settings layout (0 = new, 1 = old)")
MACRO_CONFIG_INT(PcNewColorPicker, pc_new_color_picker, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the new wheel-style color picker")
MACRO_CONFIG_INT(PcHideHudInSettings, pc_hide_hud_in_settings, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide HUD while settings page is open")
MACRO_CONFIG_INT(PcEyeComfort, pc_eye_comfort, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render a warm yellow screen overlay to reduce eye strain")
MACRO_CONFIG_INT(PcEyeComfortStrength, pc_eye_comfort_strength, 35, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Eye comfort intensity in percent; increases warmth and lowers brightness together")
MACRO_CONFIG_INT(PcEscPlayerList, pc_esc_player_list, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show players list in ESC game tab")
MACRO_CONFIG_INT(PcShowPointsInTab, pc_show_points_in_tab, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show DDNet points in the scoreboard between player name and clan")
MACRO_CONFIG_INT(PcProaledClientSettingsTabs, pc_proaledclient_settings_tabs, 0, 0, 65536, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bit flags to disable ProaledClient settings tabs")
MACRO_CONFIG_INT(PcEmoticonShadow, pc_emoticon_shadow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Draw shadow behind emoticons")
MACRO_CONFIG_INT(PcChatSaveDraft, pc_chat_save_draft, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep unfinished chat input when closing chat")
MACRO_CONFIG_INT(PcSilentTyping, pc_silent_typing, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide PLAYERFLAG_CHATTING from others while typing")
MACRO_CONFIG_INT(PcChatAltCommandLayout, pc_chat_alt_command_layout, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Interpret slash chat commands typed in the Russian keyboard layout")
MACRO_CONFIG_INT(PcScoreboardTeamGradients, pc_scoreboard_team_gradients, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render scoreboard team colors with a left-to-right gradient")
MACRO_CONFIG_INT(PcShowhudDummyCoordIndicator, pc_showhud_dummy_coord_indicator, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show player-below indicator in ingame HUD")
MACRO_CONFIG_COL(PcShowhudDummyCoordIndicatorColor, pc_showhud_dummy_coord_indicator_color, 65407, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player-below indicator color")
MACRO_CONFIG_COL(PcShowhudDummyCoordIndicatorSameHeightColor, pc_showhud_dummy_coord_indicator_same_height_color, 5635967, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player-below indicator color when aligned vertically")
MACRO_CONFIG_INT(PcShowRealHitbox, pc_show_real_hitbox, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show a dot at the center of your real hitbox")
MACRO_CONFIG_COL(PcShowRealHitboxColor, pc_show_real_hitbox_color, 0xFFFFFFFFU, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Color of the real hitbox center dot")

MACRO_CONFIG_INT(PcAutoServerListRefresh, pc_auto_server_list_refresh, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically refresh the server browser list while a browser tab is open")
MACRO_CONFIG_INT(PcAutoServerListRefreshSeconds, pc_auto_server_list_refresh_seconds, 10, 1, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto refresh interval for the server browser list in seconds")
MACRO_CONFIG_INT(PcMastersrv, pc_mastersrv, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the ProaledClient master server mirror for the server browser")
MACRO_CONFIG_INT(PcUseShortKogServerName, pc_use_short_kog_server_name, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use short name for KoG gores servers in browser list")
MACRO_CONFIG_INT(PcStreamerFlags, pc_streamer_flags, 64, 0, 127, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of ProaledClient streamer mode options")

// Auto update
MACRO_CONFIG_INT(PcAutoUpdate, pc_auto_update, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically download and apply updates on startup")

// Fast input
MACRO_CONFIG_INT(PcFastInputMode, pc_fast_input_mode, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fast input mode (0 = fast input, 1 = delta input, 3 = best input, 4 = saiko+; legacy gamma mode maps to best input)")
MACRO_CONFIG_INT(PcFastInputDeltaInput, pc_fast_input_delta_input, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delta input amount in 0.01 ticks")
MACRO_CONFIG_INT(PcFastInputGammaInput, pc_fast_input_gamma_input, 0, 0, 600, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legacy gamma input amount in 0.01 ticks (unused)")
MACRO_CONFIG_INT(PcSaikoPlusAmount, pc_saiko_plus_amount, 0, 0, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Saiko+ input amount in 0.01 ticks")
MACRO_CONFIG_INT(PcBestInputPreset, pc_best_input_preset, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input preset (0 = custom, 3 = auto; legacy values preserved for compatibility)")
MACRO_CONFIG_INT(PcBestInputOffset, pc_best_input_offset, 0, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input prediction offset in 0.01 ticks (0-10.00 ticks)")
MACRO_CONFIG_INT(PcBestInputSmoothing, pc_best_input_smoothing, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input smoothing amount (0-100%)")
MACRO_CONFIG_INT(PcBestInputLatencyComp, pc_best_input_latency_comp, 0, 0, 50, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input latency compensation (0-50%)")
MACRO_CONFIG_INT(PcBestInputInterpolation, pc_best_input_interpolation, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Best input interpolation mode (1 = linear, 2 = cubic, 3 = smooth)")
MACRO_CONFIG_INT(PcDeltaInputOthers, pc_delta_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply delta input to other tees")
MACRO_CONFIG_INT(PcGammaInputOthers, pc_gamma_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Legacy gamma input toggle for other tees (unused)")
MACRO_CONFIG_INT(PcBestInputOthers, pc_best_input_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply best input to other tees")
MACRO_CONFIG_INT(PcSaikoPlusOthers, pc_saiko_plus_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply Saiko+ input to other tees")
MACRO_CONFIG_INT(PcFastInputAutoMargin, pc_fast_input_auto_margin, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically adjusts prediction margin in real time for fast input, latency and connection stability")
MACRO_CONFIG_INT(PcSnapTap, pc_snap_tap, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Snap Tap for opposite left/right inputs")
MACRO_CONFIG_INT(PcSnapTapDelay, pc_snap_tap_delay, 0, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Snap Tap direction switch delay in milliseconds (0 = off)")
MACRO_CONFIG_INT(PcKeystrokesKeyboard, pc_keystrokes_keyboard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show keyboard keystrokes HUD")
MACRO_CONFIG_INT(PcKeystrokesKeyboardPreset, pc_keystrokes_keyboard_preset, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keyboard keystrokes preset (0 = wasd-minimal, 1 = wasd-full, 2 = micro)")
MACRO_CONFIG_INT(PcKeystrokesMouse, pc_keystrokes_mouse, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show mouse keystrokes HUD")
MACRO_CONFIG_INT(PcKeystrokesMousePreset, pc_keystrokes_mouse_preset, 0, 0, 4, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mouse keystrokes preset (0 = mouse-dot, 1 = mouse-arrow, 2 = mouse-dot-dot, 3 = mouse-dot-no-box, 4 = mouse-no-movement)")

// Auto team lock
MACRO_CONFIG_INT(PcAutoTeamLock, pc_auto_team_lock, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically lock your team after joining it")
MACRO_CONFIG_INT(PcAutoTeamLockDelay, pc_auto_team_lock_delay, 5, 0, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delay before auto-locking team after joining, in seconds")

// Extend zoom
MACRO_CONFIG_INT(PcExtendZoom, pc_extend_zoom, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use 0.5 zoom steps instead of 1 for finer scroll zoom (10, 9.5, 9, 8.5 ...)")

// Speedrun timer
MACRO_CONFIG_INT(PcSpeedrunTimer, pc_speedrun_timer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer")
MACRO_CONFIG_INT(PcSpeedrunTimerTime, pc_speedrun_timer_time, 0, 0, 9999, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer time (MMSS format)")
MACRO_CONFIG_INT(PcSpeedrunTimerHours, pc_speedrun_timer_hours, 0, 0, 99, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer hours")
MACRO_CONFIG_INT(PcSpeedrunTimerMinutes, pc_speedrun_timer_minutes, 0, 0, 59, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer minutes")
MACRO_CONFIG_INT(PcSpeedrunTimerSeconds, pc_speedrun_timer_seconds, 0, 0, 59, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer seconds")
MACRO_CONFIG_INT(PcSpeedrunTimerMilliseconds, pc_speedrun_timer_milliseconds, 0, 0, 999, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Speedrun timer milliseconds")
MACRO_CONFIG_INT(PcSpeedrunTimerAutoDisable, pc_speedrun_timer_auto_disable, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable speedrun timer automatically when time ends")
MACRO_CONFIG_INT(PcFinishPrediction, pc_finish_prediction, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable finish prediction")
MACRO_CONFIG_INT(PcFinishPredictionMode, pc_finish_prediction_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction HUD mode (0=classic, 1=progress bar)")
MACRO_CONFIG_INT(PcFinishPredictionShowAlways, pc_finish_prediction_show_always, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction even before race start")
MACRO_CONFIG_INT(PcFinishPredictionTimeMode, pc_finish_prediction_time_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Finish prediction time mode (0=remaining, 1=predicted finish time)")
MACRO_CONFIG_INT(PcFinishPredictionShowTime, pc_finish_prediction_show_time, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction time")
MACRO_CONFIG_INT(PcFinishPredictionShowPercentage, pc_finish_prediction_show_percentage, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction progress percentage")
MACRO_CONFIG_INT(PcFinishPredictionShowMillis, pc_finish_prediction_show_millis, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show finish prediction milliseconds")
MACRO_CONFIG_INT(PcFinishPredictionBarCustomColor, pc_finish_prediction_bar_custom_color, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use a custom finish prediction progress bar color")
MACRO_CONFIG_COL(PcFinishPredictionBarColor, pc_finish_prediction_bar_color, 0xFFFFFFFF, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Finish prediction progress bar custom color")

// Admin panel
MACRO_CONFIG_INT(PcAdminPanelAutoScroll, pc_adminpanel_autoscroll, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Auto-scroll logs in admin panel")
MACRO_CONFIG_INT(PcAdminPanelRememberTab, pc_adminpanel_remember_tab, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Remember last active admin panel tab")
MACRO_CONFIG_INT(PcAdminPanelLastTab, pc_adminpanel_last_tab, 0, 0, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Last active admin panel tab")
MACRO_CONFIG_INT(PcAdminPanelDisableAnim, pc_adminpanel_disable_anim, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable admin panel animations")
MACRO_CONFIG_INT(PcAdminPanelScale, pc_adminpanel_scale, 100, 80, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel scale in percent")
MACRO_CONFIG_INT(PcAdminPanelLogLines, pc_adminpanel_log_lines, 200, 50, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum lines to keep in admin panel logs")
MACRO_CONFIG_INT(PcAdminPanelRconLog, pc_adminpanel_rcon_log, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Log F2 console (rcon) output to rcon-log.txt in DDNet appdata")
MACRO_CONFIG_COL(PcAdminPanelBgColor, pc_adminpanel_bg_color, 0x8C000000, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Admin panel background color")
MACRO_CONFIG_COL(PcAdminPanelTabInactiveColor, pc_adminpanel_tab_inactive_color, 0xCC1A001A, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Admin panel inactive tab color")
MACRO_CONFIG_COL(PcAdminPanelTabActiveColor, pc_adminpanel_tab_active_color, 0xE6B40069, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Admin panel active tab color")
MACRO_CONFIG_COL(PcAdminPanelTabHoverColor, pc_adminpanel_tab_hover_color, 0xE6FF69B4, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Admin panel hover tab color")
MACRO_CONFIG_STR(PcAdminFastAction0, pc_admin_fast_action0, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 1")
MACRO_CONFIG_STR(PcAdminFastAction1, pc_admin_fast_action1, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 2")
MACRO_CONFIG_STR(PcAdminFastAction2, pc_admin_fast_action2, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 3")
MACRO_CONFIG_STR(PcAdminFastAction3, pc_admin_fast_action3, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 4")
MACRO_CONFIG_STR(PcAdminFastAction4, pc_admin_fast_action4, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 5")
MACRO_CONFIG_STR(PcAdminFastAction5, pc_admin_fast_action5, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 6")
MACRO_CONFIG_STR(PcAdminFastAction6, pc_admin_fast_action6, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 7")
MACRO_CONFIG_STR(PcAdminFastAction7, pc_admin_fast_action7, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 8")
MACRO_CONFIG_STR(PcAdminFastAction8, pc_admin_fast_action8, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 9")
MACRO_CONFIG_STR(PcAdminFastAction9, pc_admin_fast_action9, 96, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Admin panel fast action command slot 10")

// Music player
MACRO_CONFIG_INT(PcMusicPlayer, pc_music_player, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable Music Player HUD element")
MACRO_CONFIG_INT(PcMusicPlayerShowWhenPaused, pc_music_player_show_when_paused, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Keep Music Player visible while playback is paused")
MACRO_CONFIG_INT(PcMusicPlayerVisualizer, pc_music_player_visualizer, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable music player visualizer")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerMode, pc_music_player_visualizer_mode, 1, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer mode (0=bottom, 1=center, 2=up)")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerSensitivity, pc_music_player_visualizer_sensitivity, 300, 50, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer sensitivity in percent (higher catches quieter audio)")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerSmoothing, pc_music_player_visualizer_smoothing, 50, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer smoothing (0-100)")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerRounding, pc_music_player_visualizer_rounding, 0, 0, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer rounding in percent")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerColumns, pc_music_player_visualizer_columns, 5, 5, 10, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer bar count")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerColumnWidth, pc_music_player_visualizer_column_width, 100, 50, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer column width in percent")
MACRO_CONFIG_INT(PcMusicPlayerVisualizerGap, pc_music_player_visualizer_gap, 100, 0, 250, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player visualizer gap in percent")
MACRO_CONFIG_INT(PcMusicPlayerColorMode, pc_music_player_color_mode, 3, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player color mode (0=static color, 1=cover accent color, 2=dominant cover color, 3=translucent)")
MACRO_CONFIG_COL(PcMusicPlayerStaticColor, pc_music_player_static_color, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Static color for the music player when static color mode is selected")
MACRO_CONFIG_INT(PcMusicPlayerSizeMode, pc_music_player_size_mode, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player size mode (0=normal, 1=mini)")
MACRO_CONFIG_INT(PcMusicPlayerTextScale, pc_music_player_text_scale, 100, 70, 150, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player text scale in percent")
MACRO_CONFIG_INT(PcMusicPlayerAnimationMs, pc_music_player_animation_ms, 180, 50, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Music player animation duration in milliseconds")
MACRO_CONFIG_INT(PcMusicPlayerShowCover, pc_music_player_show_cover, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show cover art in the music player")
MACRO_CONFIG_INT(PcMusicPlayerUseColorForHud, pc_music_player_use_color_for_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use the Music Player color for HUD rectangles in hud.cpp")
MACRO_CONFIG_INT(PcMusicPlayerHudColorAlpha, pc_music_player_hud_color_alpha, 100, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Alpha multiplier for the Music Player and HUD colors")
MACRO_CONFIG_INT(PcHudMusicPlayerX, pc_hud_music_player_x, 198, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD editor X position for music player")
MACRO_CONFIG_INT(PcHudMusicPlayerY, pc_hud_music_player_y, 0, -1000, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD editor Y position for music player")
MACRO_CONFIG_INT(PcHudMusicPlayerScale, pc_hud_music_player_scale, 100, 25, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "HUD editor scale for music player")
MACRO_CONFIG_INT(PcHudVoiceHudX, pc_hud_voice_hud_x, 4, -1000, 1000, CFGFLAG_CLIENT, "HUD editor X position for voice HUD")
MACRO_CONFIG_INT(PcHudVoiceHudY, pc_hud_voice_hud_y, 122, -1000, 1000, CFGFLAG_CLIENT, "HUD editor Y position for voice HUD")
MACRO_CONFIG_INT(PcHudVoiceHudScale, pc_hud_voice_hud_scale, 100, 25, 300, CFGFLAG_CLIENT, "HUD editor scale for voice HUD")
MACRO_CONFIG_INT(PcHudVoiceMuteIconsX, pc_hud_voice_mute_icons_x, 136, -1000, 1000, CFGFLAG_CLIENT, "HUD editor X position for voice mute icons")
MACRO_CONFIG_INT(PcHudVoiceMuteIconsY, pc_hud_voice_mute_icons_y, 0, -1000, 1000, CFGFLAG_CLIENT, "HUD editor Y position for voice mute icons")
MACRO_CONFIG_INT(PcHudVoiceMuteIconsScale, pc_hud_voice_mute_icons_scale, 100, 25, 300, CFGFLAG_CLIENT, "HUD editor scale for voice mute icons")
MACRO_CONFIG_INT(PcHudChatX, pc_hud_chat_x, 5, -1000, 1000, CFGFLAG_CLIENT, "HUD editor X position for ingame chat")
MACRO_CONFIG_INT(PcHudChatY, pc_hud_chat_y, 278, -1000, 1000, CFGFLAG_CLIENT, "HUD editor Y anchor position for ingame chat")
MACRO_CONFIG_INT(PcHudChatScale, pc_hud_chat_scale, 100, 25, 300, CFGFLAG_CLIENT, "HUD editor scale for ingame chat")
MACRO_CONFIG_INT(PcHudVotesX, pc_hud_votes_x, 0, -1000, 1000, CFGFLAG_CLIENT, "HUD editor X position for votes")
MACRO_CONFIG_INT(PcHudVotesY, pc_hud_votes_y, 60, -1000, 1000, CFGFLAG_CLIENT, "HUD editor Y position for votes")
MACRO_CONFIG_INT(PcHudVotesScale, pc_hud_votes_scale, 100, 25, 300, CFGFLAG_CLIENT, "HUD editor scale for votes")
MACRO_CONFIG_INT(PcDisabledComponentsMaskLo, pc_disabled_components_mask_lo, 0, 0, 2147483647, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Low bitmask for disabled components")
MACRO_CONFIG_INT(PcDisabledComponentsMaskHi, pc_disabled_components_mask_hi, 0, 0, 2147483647, CFGFLAG_CLIENT | CFGFLAG_SAVE, "High bitmask for disabled components")

// Voice chat
MACRO_CONFIG_INT(PcVoiceChatEnable, pc_voice_chat_enable, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable integrated voice chat")
MACRO_CONFIG_INT(PcVoiceChatActivationMode, pc_voice_chat_activation_mode, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice activation mode (0 = automatic activation, 1 = push-to-talk)")
MACRO_CONFIG_INT(PcVoiceChatVadThreshold, pc_voice_chat_vad_threshold, 5, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice activation threshold in automatic mode (percent)")
MACRO_CONFIG_INT(PcVoiceChatVadReleaseDelayMs, pc_voice_chat_vad_release_delay_ms, 150, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Delay before automatic voice activation turns off (ms)")
MACRO_CONFIG_INT(PcVoiceChatVolume, pc_voice_chat_volume, 100, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice playback volume in percent")
MACRO_CONFIG_INT(PcVoiceChatMicGain, pc_voice_chat_mic_gain, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Microphone gain in percent")
MACRO_CONFIG_INT(PcVoiceChatBitrate, pc_voice_chat_bitrate, 96, 6, 128, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice Opus bitrate in kbps")
MACRO_CONFIG_INT(PcVoiceChatInputDevice, pc_voice_chat_input_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice input device index (-1 = system default)")
MACRO_CONFIG_INT(PcVoiceChatOutputDevice, pc_voice_chat_output_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice output device index (-1 = system default)")
MACRO_CONFIG_INT(PcVoiceChatMicMuted, pc_voice_chat_mic_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice microphone")
MACRO_CONFIG_INT(PcVoiceChatHeadphonesMuted, pc_voice_chat_headphones_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice playback")
MACRO_CONFIG_INT(PcVoiceChatMicCheck, pc_voice_chat_mic_check, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable microphone check (local loopback)")
MACRO_CONFIG_INT(PcVoiceChatInGameOnly, pc_voice_chat_ingame_only, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Only allow voice transmit/playback while the game window is active")
MACRO_CONFIG_INT(PcVoiceChatUseTeam0, pc_voice_chat_use_team0, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Force voice chat to use team 0 even while you are in a team")
MACRO_CONFIG_INT(PcVoiceChatEnableYourGroup, pc_voice_chat_enable_your_group, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "In team0 mode, also include your own team for voice transmit/playback")
MACRO_CONFIG_INT(PcVoiceChatRadiusEnabled, pc_voice_chat_radius_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable local voice radius filter")
MACRO_CONFIG_INT(PcVoiceChatRadiusTiles, pc_voice_chat_radius_tiles, 25, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice radius in tiles when local radius filter is enabled")
MACRO_CONFIG_INT(PcVoiceChatNameplateIcon, pc_voice_chat_nameplate_icon, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show microphone icon in name plates for talking players")
MACRO_CONFIG_STR(PcVoiceChatServerAddress, pc_voice_chat_server_address, 128, "managed", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice server address")
MACRO_CONFIG_STR(PcVoiceChatMutedNames, pc_voice_chat_muted_names, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of muted voice nicknames (case-insensitive)")
MACRO_CONFIG_STR(PcVoiceChatNameVolumes, pc_voice_chat_name_volumes, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of voice nickname volumes in percent (name=value, case-insensitive)")
MACRO_CONFIG_STR(PcVoiceModKey, pc_voice_mod_key, 128, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice moderation key (saved for convenience)")

MACRO_CONFIG_INT(PcMenuSfx, pc_menu_sfx, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable ProaledClient menu sound effects")
MACRO_CONFIG_INT(PcMenuSfxVolume, pc_menu_sfx_volume, 70, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "ProaledClient menu sound effects volume")

// Media background
MACRO_CONFIG_INT(PcMenuMediaBackground, pc_menu_media_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable custom media background in offline menus")
MACRO_CONFIG_INT(PcGameMediaBackground, pc_game_media_background, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable custom media background in game background rendering")
MACRO_CONFIG_STR(PcMenuMediaBackgroundPath, pc_menu_media_background_path, IO_MAX_PATH_LENGTH, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Path to the custom menu media background file")
MACRO_CONFIG_INT(PcGameMediaBackgroundOffset, pc_game_media_background_offset, 0, 0, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How much the custom media background is fixed to the map when rendering the in-game background")
MACRO_CONFIG_INT(PcMotionBlur, pc_motion_blur, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable motion blur via previous-frame blending")
MACRO_CONFIG_INT(PcMotionBlurStrength, pc_motion_blur_strength, 50, 0, 95, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of motion blur frame blending (0-95%)")

// Jelly tee
MACRO_CONFIG_INT(PcJellyTee, pc_jelly_tee, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable jelly tee deformation")
MACRO_CONFIG_INT(PcJellyTeeOthers, pc_jelly_tee_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply jelly tee deformation to other players")
MACRO_CONFIG_INT(PcJellyTeeStrength, pc_jelly_tee_strength, 500, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Strength of jelly tee deformation")
MACRO_CONFIG_INT(PcJellyTeeDuration, pc_jelly_tee_duration, 30, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Duration of jelly tee deformation")

// Player trail
MACRO_CONFIG_INT(PcTrail, pc_trail, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable player trail effect")
MACRO_CONFIG_INT(PcTrailOthers, pc_trail_others, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show player trail for other players")
MACRO_CONFIG_INT(PcTrailMode, pc_trail_mode, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player trail mode (0=grenade, 1=invisible, 2=ninja)")


// Client Indicator
MACRO_CONFIG_INT(PcClientIndicator, pc_client_indicator, 1, 1, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator is always enabled")
MACRO_CONFIG_INT(PcClientIndicatorVersions, pc_client_indicator_versions, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show versions tab in ProaledClient server browser panel")
MACRO_CONFIG_INT(DbgClientIndicator, dbg_client_indicator, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Debug logging for ProaledClient indicator (1=verbose, 2=dump all UDP packet bytes sent/received)")
MACRO_CONFIG_INT(DbgMusicPlayer, dbg_music_player, 0, 0, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Debug logging for music player (0=off, 1=state changes, 2=verbose periodic diagnostics)")
MACRO_CONFIG_INT(PcNameplateVoiceOffsetX, pc_nameplate_voice_offset_x, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Horizontal offset for the voice icon in nameplates")
MACRO_CONFIG_INT(PcNameplateVoiceOffsetY, pc_nameplate_voice_offset_y, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vertical offset for the voice icon in nameplates")
MACRO_CONFIG_INT(PcNameplateClientIndicatorOffsetX, pc_nameplate_client_indicator_offset_x, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Horizontal offset for the client indicator in nameplates")
MACRO_CONFIG_INT(PcNameplateClientIndicatorOffsetY, pc_nameplate_client_indicator_offset_y, 0, -400, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Vertical offset for the client indicator in nameplates")
MACRO_CONFIG_INT(PcNameplateGradient, pc_nameplate_gradient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Gradient nameplate colors based on skin body and feet colors")
MACRO_CONFIG_INT(PcFlyingNamePlates, pc_flying_name_plates, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render name plates like flying kites attached to players")
MACRO_CONFIG_INT(PcFlyingNamePlatesLift, pc_flying_name_plates_lift, 28, 0, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Extra vertical lift for flying name plates")
MACRO_CONFIG_INT(PcFlyingNamePlatesDrag, pc_flying_name_plates_drag, 52, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How far flying name plates trail behind movement")
MACRO_CONFIG_INT(PcFlyingNamePlatesFollow, pc_flying_name_plates_follow, 40, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How quickly flying name plates catch up to their target position")
MACRO_CONFIG_INT(PcClientIndicatorInNamePlate, pc_client_indicator_in_name_plate, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator in name plate")
MACRO_CONFIG_INT(PcClientIndicatorInNamePlateAboveSelf, pc_client_indicator_in_name_plate_above_self, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator above self")
MACRO_CONFIG_INT(PcClientIndicatorInNamePlateSize, pc_client_indicator_in_name_plate_size, 30, -50, 100, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Client indicator in name plate size")
MACRO_CONFIG_INT(PcClientIndicatorInNamePlateDynamic, pc_client_indicator_in_name_plate_dynamic, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator in nameplates will dynamically change pos")
MACRO_CONFIG_INT(IndicatorVersion, indicator_version, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show ProaledClient version in name plates")
MACRO_CONFIG_INT(PcClientIndicatorInScoreboard, pc_client_indicator_in_scoreboard, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show client indicator in name plate")
MACRO_CONFIG_INT(PcClientIndicatorInSoreboardSize, pc_client_indicator_in_scoreboard_size, 100, -50, 100, CFGFLAG_SAVE | CFGFLAG_CLIENT, "Client indicator in name plate size")
MACRO_CONFIG_STR(PcClientIndicatorServerAddress, pc_client_indicator_server_address, 256, "150.241.70.188:8778", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator UDP presence server")
MACRO_CONFIG_STR(PcClientIndicatorBrowserUrl, pc_client_indicator_browser_url, 256, "https://150.241.70.188:8779/users.json", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator browser JSON URL")
MACRO_CONFIG_STR(PcClientIndicatorTokenUrl, pc_client_indicator_token_url, 256, "https://150.241.70.188:8779/token.json", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator token bootstrap URL")
MACRO_CONFIG_STR(PcClientIndicatorSharedToken, pc_client_indicator_shared_token, 256, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator shared token for signed UDP packets")
MACRO_CONFIG_STR(PcClientIndicatorSecretKey, pc_client_indicator_secret_key, 256, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Client indicator developer secret key")
MACRO_CONFIG_INT(BrFilterBestclient, br_filter_proaledclient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Filter out servers with no ProaledClient users")

// Optimizer
MACRO_CONFIG_INT(PcOptimizer, pc_optimizer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable optimizer features")
MACRO_CONFIG_INT(PcOptimizerDisableParticles, pc_optimizer_disable_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Disable rendering/updating all particles")
MACRO_CONFIG_INT(PcOptimizerFpsFog, pc_optimizer_fps_fog, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cull non-map rendering outside a distance limit around the camera")
MACRO_CONFIG_INT(PcOptimizerDdnetPriorityHigh, pc_optimizer_ddnet_priority_high, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set DDNet process priority to High while enabled")
MACRO_CONFIG_INT(PcOptimizerDiscordPriorityBelowNormal, pc_optimizer_discord_priority_below_normal, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Set Discord process priority to Below Normal while enabled")
MACRO_CONFIG_INT(PcOptimizerFpsFogMode, pc_optimizer_fps_fog_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog mode (0=manual radius tiles, 1=by zoom percent)")
MACRO_CONFIG_INT(PcOptimizerFpsFogRadiusTiles, pc_optimizer_fps_fog_radius_tiles, 40, 5, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog manual radius in tiles (tile=32 units)")
MACRO_CONFIG_INT(PcOptimizerFpsFogZoomPercent, pc_optimizer_fps_fog_zoom_percent, 70, 10, 120, CFGFLAG_CLIENT | CFGFLAG_SAVE, "FPS fog visible area percent in zoom mode")
MACRO_CONFIG_INT(PcOptimizerFpsFogRenderRect, pc_optimizer_fps_fog_render_rect, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Render an outline rectangle showing the FPS fog area")
MACRO_CONFIG_INT(PcOptimizerFpsFogCullMapTiles, pc_optimizer_fps_fog_cull_map_tiles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Cull map tile rendering outside the FPS fog area")

// Focus Mode Settings
MACRO_CONFIG_INT(ClFocusMode, p_focus_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable focus mode to minimize visual distractions")
MACRO_CONFIG_INT(ClFocusModeHideNames, p_focus_mode_hide_names, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide player names in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideEffects, p_focus_mode_hide_effects, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide visual effects in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideHud, p_focus_mode_hide_hud, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide HUD in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideSongPlayer, p_focus_mode_hide_song_player, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide song player in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideUI, p_focus_mode_hide_ui, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide unnecessary UI elements in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideChat, p_focus_mode_hide_chat, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide chat in focus mode")
MACRO_CONFIG_INT(ClFocusModeHideScoreboard, p_focus_mode_hide_scoreboard, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Hide scoreboard in focus mode")

//Effects controls
MACRO_CONFIG_INT(ClFreezeSnowFlakes, p_effect_freeze_snowflakes, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "toggles snowflakes effect")
MACRO_CONFIG_INT(ClHammerHitEffect, p_effect_hammerhit, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "toggles hammer hit effect")
MACRO_CONFIG_INT(ClHammerHitEffectSound, p_effect_sound_hammerhit, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "toggles hammer hit effect")
MACRO_CONFIG_INT(ClJumpEffect, p_effect_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "toggles hammer hit effect")
MACRO_CONFIG_INT(ClJumpEffectSound, p_effect_sound_jump, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "toggles jump effect sound")
MACRO_CONFIG_INT(PcMuteOthersHook, pc_mute_others_hook, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute hook sounds of other players")
MACRO_CONFIG_INT(PcMuteOthersHammer, pc_mute_others_hammer, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute hammer sounds of other players")

// 3D particles
MACRO_CONFIG_INT(Bc3dParticles, pc_3d_particles, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Toggle 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesType, pc_3d_particles_type, 1, 1, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Type of 3D particles. 1 = Cube, 2 = Heart, 3 = Mixed")
MACRO_CONFIG_INT(Bc3dParticlesCount, pc_3d_particles_count, 60, 1, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Count of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesSizeMin, pc_3d_particles_size_min, 3, 2, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minimum size of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesSizeMax, pc_3d_particles_size_max, 8, 2, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Maximum size of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesSpeed, pc_3d_particles_speed, 18, 1, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Base speed of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesDepth, pc_3d_particles_depth, 300, 10, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Depth range for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesAlpha, pc_3d_particles_alpha, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Alpha of 3D particles (1-100)")
MACRO_CONFIG_INT(Bc3dParticlesFadeInMs, pc_3d_particles_fade_in_ms, 400, 1, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fade-in time in ms for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesFadeOutMs, pc_3d_particles_fade_out_ms, 400, 1, 5000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Fade-out time in ms for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesPushRadius, pc_3d_particles_push_radius, 120, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player push radius for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesPushStrength, pc_3d_particles_push_strength, 120, 0, 2000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Player push strength for 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesCollide, pc_3d_particles_collide, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "3D particles collide with each other")
MACRO_CONFIG_INT(Bc3dParticlesViewMargin, pc_3d_particles_view_margin, 120, 0, 1000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Margin outside view before 3D particles disappear")
MACRO_CONFIG_INT(Bc3dParticlesColorMode, pc_3d_particles_color_mode, 1, 1, 2, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Color mode for 3D particles. 1 = Custom, 2 = Random")
MACRO_CONFIG_COL(Bc3dParticlesColor, pc_3d_particles_color, 4294967295, CFGFLAG_CLIENT | CFGFLAG_SAVE | CFGFLAG_COLALPHA, "Color of 3D particles")
MACRO_CONFIG_INT(Bc3dParticlesGlow, pc_3d_particles_glow, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable 3D particles glow")
MACRO_CONFIG_INT(Bc3dParticlesGlowAlpha, pc_3d_particles_glow_alpha, 35, 1, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Glow alpha of 3D particles (1-100)")

// Casino
MACRO_CONFIG_INT(PcCasinoBalance, pc_casino_balance, 500, 0, 9999999, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Casino game balance in dollars")
MACRO_CONFIG_INT(PcCasinoLastClaim, pc_casino_last_claim, 0, 0, 2147483647, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Unix timestamp of last casino free claim")
MACRO_CONFIG_INT(Bc3dParticlesGlowOffset, pc_3d_particles_glow_offset, 2, 1, 20, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Glow offset for 3D particles")
