if(NOT DEFINED TAR_EXECUTABLE)
  message(FATAL_ERROR "TAR_EXECUTABLE is required")
endif()

if(NOT DEFINED ARCHIVE_FORMAT)
  message(FATAL_ERROR "ARCHIVE_FORMAT is required")
endif()

if(NOT DEFINED ARCHIVE_OUTPUT)
  message(FATAL_ERROR "ARCHIVE_OUTPUT is required")
endif()

if(NOT DEFINED ARCHIVE_SOURCE_DIR)
  message(FATAL_ERROR "ARCHIVE_SOURCE_DIR is required")
endif()

if(NOT DEFINED ARCHIVE_SOURCE_NAME)
  message(FATAL_ERROR "ARCHIVE_SOURCE_NAME is required")
endif()

if(ARCHIVE_FORMAT STREQUAL "tar.gz")
  set(ARCHIVE_FLAGS -czf)
elseif(ARCHIVE_FORMAT STREQUAL "tar.xz")
  set(ARCHIVE_FLAGS -cJf)
else()
  message(FATAL_ERROR "Unsupported archive format: ${ARCHIVE_FORMAT}")
endif()

execute_process(
  COMMAND ${TAR_EXECUTABLE} ${ARCHIVE_FLAGS} ${ARCHIVE_OUTPUT} ${ARCHIVE_SOURCE_NAME}
  WORKING_DIRECTORY ${ARCHIVE_SOURCE_DIR}
  RESULT_VARIABLE ARCHIVE_RESULT
)

if(NOT ARCHIVE_RESULT EQUAL 0)
  message(FATAL_ERROR "Failed to create archive ${ARCHIVE_OUTPUT}")
endif()
